# Site Settings
title:               "Peter's codebook"
tagline:             A blog full of codes
description:
baseurl:            "/ContestCo"
url:                "https://peter0749.github.io"
github:
  url:               #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Kuang-Yu Jeng"
  email:             "jengku@gmail.com"
  twitter:           ""
  instagram:         ""
  github:            "peter0749"
  facebook:          "peter0749"
  linkedin:          "光宇-鄭-403958128"
navigation:
- title: 關於這裡
  url: /about
- title: 文章
  url: /writing
- title: 聯絡我
  url: /contact

paginate:            5
disqus:              "https-peter0749-github-io-contestco"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
